### PR TITLE
support inline-flex. fixes #107

### LINKED ISSUE #107: Support for other flex values
I cloned this repo and saw that it looks for `flex` specifically.

What about `inline-flex`?

### PR DESCRIPTION
**Pull request by idanen**

### CODE REVIEW

**Comment by 7rulnik** [comment]
@idanen hey!
Nice catch, thank you. I will merge it tomorrow

**Comment by idanen** [comment]
Added small change to prevent adding `-js-display` when the rule has browser prefix like `display: -webkit-flex;`.

Now just adding for `flex` and `inline-flex` instead of everything with "flex"

**Comment by idanen** [comment]
Hey @7rulnik , any idea why the coverage check doesn't finish?

**Comment by idanen** [comment]
Hi @7rulnik, do you have an ETA for when will you merge this?

Thanks

**Comment by 7rulnik** [comment]
@idanen sorry, I was on vacation. Want to release it today.

**Comment by 7rulnik** [comment]
@idanen just released in [v.2.0.0](https://github.com/7rulnik/postcss-flexibility/releases/tag/v2.0.0)

**Comment by idanen** [comment]
Awesome! Thanks for the update 👌

**Pull request merged**
